### ISSUE TITLE
Integrate S3 for images

### ISSUE THREAD

**Issue by joshuaellinger** [COVID19Tracking/covid-data-pipeline#2]
Add a new file/class that pushes image data to S3 using a standard naming convention.

It should be like DirectoryCache with methods like:
    read/write/delete/list
but write is all we need for now.

Then make the screenshot routine push to that location.

Let's get the keys from the env for now.  if the keys aren't present, print a warning and skip the push

**Comment by joshuaellinger** [comment]
Can we close this?

**Comment by julia326** [comment]
Yep!
