### ISSUE TITLE
cannot import name 'get_available_sources'

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/covid-data-pipeline#6]
1. I just performed a fresh install
2. `git checkout dev`
3. `python tests/test_sources.py`
Returns:
```
Traceback (most recent call last):
  File "tests/test_sources.py", line 10, in <module>
    from url_source import UrlSource, get_available_sources
ImportError: cannot import name 'get_available_sources' from 'url_source' (<<my file path>>\url_source.py)
```

For what it's worth:

```
$ grep -r "get_available_sources" .
./tests/test_sources.py:from url_source import UrlSource, get_available_sources
./tests/test_sources.py:    sources = get_available_sources()
```

It doesn't seem like `get_available_sources` is used anywhere outside of `test_sources`.

Am I missing something or is this an actual issue?

**Comment by joshuaellinger** [comment]
lost something in a merge.  fixing.

**Comment by schwartzadev** [comment]
Got it. Thanks!

**Comment by joshuaellinger** [comment]
Actually, I just forgot to run it after changing the code structure.  It's working for me now.

The UrlSourceManager loads UrlSources, reruns an update, then runs it thought UrlSourceValidator to check that its okay.  Logs are written to c:\\temp\\source.

sources.txt is a persisted data frame.  your source should say that its valid after the run.
your data gets stored in <<name>>.txt

the whole thing belongs in a DB but I'm waiting on credits from DO before setting up.
